apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pam-samtykke-api-tokenx-proxy
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{image}}
  liveness:
    path: /isalive
    port: 8080
    initialDelay: 10
    timeout: 60
  readiness:
    path: /isready
    port: 8080
    initialDelay: 10
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi

  accessPolicy:
    outbound:
      rules:
        - application: pam-samtykke-api
