name: Build and deploy
on:
  push:
    branches:
    - main
env:
  "IMAGE": "ghcr.io/${{ github.repository }}:${{ github.sha }}"
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: "${{ github.actor }}"
        password: "${{ secrets.GITHUB_TOKEN }}"
    - name: Build and push the Docker image
      run: "docker build --pull --tag ${IMAGE} . && docker push ${IMAGE}"
  deployAppToDev:
    name: Deploy app to dev-fss
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to dev-fss
      uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: "${{ secrets.NAIS_DEPLOY_APIKEY }}"
        CLUSTER: dev-fss
        RESOURCE: .nais/nais.yml
  # deployAppToProd:
  #   name: Deploy app to prod-fss
  #   needs: deployAppToDev
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Deploy to prod-fss
  #     uses: nais/deploy/actions/deploy@v1
  #     env:
  #       APIKEY: "${{ secrets.NAIS_DEPLOY_APIKEY }}"
  #       CLUSTER: prod-fss
  #       RESOURCE: .nais/nais.yml
